input_dir = "data/graphs/ex1/"
nfa_dir = "data/nfa/ta0-4.csv"
debug =    0 # 0  For nothing - 10 for everything

pattern_type = "path2"
#pattern_type = "path3"
#pattern_type = "path4"
#pattern_type = "cycle_two"
#pattern_type = "triangles_WOJ"
#pattern_type = "rectangle_woj"

pattern_size = 2
